services:
  - type: web
    name: stem-splitter
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --timeout 600 --workers 1
    plan: free
    envVars:
      - key: DATA_DIR
        value: /mnt/data
    disk:
      name: stem-splitter-data
      mountPath: /mnt/data
      sizeGB: 1
