services:
  - type: web
    name: stem-splitter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600 --workers 1
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATA_DIR
        value: /mnt/data
    disk:
      name: stem-splitter-data
      mountPath: /mnt/data
      sizeGB: 1
