services:
  - type: web
    name: stem-splitter
    runtime: docker
    plan: free
    envVars:
      - key: DATA_DIR
        value: /mnt/data
      - key: TORCH_HOME
        value: /mnt/data/.torch
    disk:
      name: stem-splitter-data
      mountPath: /mnt/data
      sizeGB: 1
